{% set version = "1.6.0" %}
{% set python_min = "3.10" %}

package:
  name: micro_sam
  version: {{ version }}

source:
  url: https://github.com/computational-cell-analytics/micro-sam/archive/v{{ version }}.tar.gz
  sha256: 5181f7d5101c03d96ca12b9a50b50a120fe60b2d7618b36b672083e1bbc57a6d

build:
  entry_points:
    - micro_sam.annotator_2d = micro_sam.sam_annotator.annotator_2d:main
    - micro_sam.annotator_3d = micro_sam.sam_annotator.annotator_3d:main
    - micro_sam.annotator_tracking = micro_sam.sam_annotator.annotator_tracking:main
    - micro_sam.automatic_segmentation = micro_sam.automatic_segmentation:main
    - micro_sam.benchmark_sam = micro_sam.evaluation.benchmark_datasets:main
    - micro_sam.evaluate = micro_sam.evaluation.evaluation:main
    - micro_sam.image_series_annotator = micro_sam.sam_annotator.image_series_annotator:main
    - micro_sam.info = micro_sam.util:micro_sam_info
    - micro_sam.precompute_embeddings = micro_sam.precompute_state:main
    - micro_sam.train = micro_sam.training.training:main
  noarch: python
  number: 0
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - kornia
    - napari >=0.5,<0.7.0
    - nifty >=1.2.3
    - pooch
    - pyqt
    - python >={{ python_min }}
    - python-elf >=0.6.1
    - python-xxhash
    - pytorch >=2.4.0
    - segment-anything
    - torchvision
    - torch_em >=0.7.10
    - tqdm
    - timm
    - xarray
    - zarr

test:
  requires:
    - python {{ python_min }}
  imports:
    - micro_sam
  source_files:
    - test/**/*.py
  commands:
    - python -m unittest discover -s test -v

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Segment Anything for Microscopy.
  home: https://github.com/computational-cell-analytics/micro-sam

extra:
  recipe-maintainers:
    - constantinpape
