{% set version = "0.3.0post1" %}

package:
  name: micro_sam
  version: {{ version }}

source:
  url: https://github.com/computational-cell-analytics/micro-sam/archive/{{ version }}.tar.gz
  sha256: 4b9333d7be0008797838b4c597501548d7bb202e5f948858f5cb77ce72a79d92

build:
  entry_points:
    - micro_sam.annotator = micro_sam.sam_annotator.annotator:main
    - micro_sam.annotator_2d = micro_sam.sam_annotator.annotator_2d:main
    - micro_sam.annotator_3d = micro_sam.sam_annotator.annotator_3d:main
    - micro_sam.annotator_tracking = micro_sam.sam_annotator.annotator_tracking:main
    - micro_sam.image_series_annotator = micro_sam.sam_annotator.image_series_annotator:main
    - micro_sam.precompute_embeddings = micro_sam.precompute_state:main
  noarch: python
  number: 0
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - kornia
    - pooch
    - python >=3.8
    - python-elf >=0.4.8
    - pytorch
    - segment-anything
    - torchvision
    - torch_em
    - tqdm
    - zarr
  run_constrained:
    - napari >=0.4.18
    - torch_em >=0.5.2

test:
  imports:
    - micro_sam
  source_files:
    - test/**/*.py
  commands:
    - python -m unittest discover -s test -v

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Segment Anything for Microscopy.
  home: https://github.com/computational-cell-analytics/micro-sam

extra:
  recipe-maintainers:
    - constantinpape
